### ISSUE TITLE
Question why was the option to change the path to where you install impact client removed?

### ISSUE THREAD

**Issue by yodaluca** [ImpactDevelopment/Installer#103]
I notice in the new more recent installer for impact the option to change the path for it was removed. Why Is this? because I have a Minecraft+game band which pretty much allows me to play Minecraft on a USB stick and the new installer forces me to have to install it on my Minecraft on my PC then move it to my gameband which just takes more time so please Re-add this feature. It doesn’t do anyone any harm and for the people that need it in a different path can use it.

**Comment by leijurv** [comment]
Feel free to download the any older version(s) of the installer from https://github.com/ImpactDevelopment/Installer/releases

**Comment by yodaluca** [comment]
Ok but would the older versions have the option for 4.9 or whatever the newest one is and also the option for MC version for 1.15.2 and hopefully 1.16 soon???

**Comment by leijurv** [comment]
It would be faster to try it yourself than wait for me to reply. I don't know lol
