### ISSUE TITLE
Add removed features back under a separate tab or drop-down menu

### ISSUE THREAD

**Issue by valthewyvern** [ImpactDevelopment/Installer#104]
**Is your feature request related to a problem? Please describe.**
The new optifine integration is more confusing and slower to use than the old optifine integration.
Custom .minecraft filepaths are important for people using flatpaks/snaps/twitch/etc

**Describe the solution you'd like**
I would like said features to be put back into the installer, maybe under a "Legacy Options" tab or something like that so it doesn't get in the way of a "normal" install.

**Describe alternatives you've considered**
An information box on how to use the new optifine integration and how to use custom .minecraft filepaths using CLI.

**Comment by LeafHacker** [comment]
OptiFine integration was greatly improved in 0.9.1, you now have the choice between any optifine version we can find or supplying your own installer. If no optifine version is found, you only have the option to supply your own installer.

The Minecraft Launcher directory option was never removed, but was hidden from the GUI - it could still be set from the CLI. 66a2a16699f4945ab753909513347b6bbe29acea makes it visible in the GUI when the installation mode is set to `Official Launcher` (used to be called `Vanilla` mode).

This reversal was made thanks to feedback such as this issue which pointed out snaps & 3rd party launchers could change the directory. It was initially hidden on the basis that the Official Launcher when installed normally does not allow its directory to be configured or changed.
