### ISSUE TITLE
MultiMC installation does not copy OptiFine jar to the instance

### ISSUE THREAD

**Issue by ricoip** [ImpactDevelopment/Installer#107]
**Describe the bug**
When installing with MultiMC, the OptiFine jar file is not copied to the `instances/[impact version]/libraries` folder, causing MultiMC to throw a file not found error

**To Reproduce**

1. Use the Installer in MultiMC mode
2. Select Impact 4.9.1 with 1.15.2
3. Enable "Include OptiFine"
4. Select OptiFine version from the drop-down
5. Install
6. Return to MultiMC and start the new instance
7. See error

**Expected behavior**
It launches properly

**What actually happens**
It doesn't launch, citing that the OptiFine jar is missing

<details> 
  <summary><strong>Game output</strong></summary>
 

```
MultiMC version: 0.6.12-develop-1459


Minecraft folder is:
D:/Applications/MultiMC/instances/Impact-4.9-1.15.2-OptiFine-HD_U_G1_pre26/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


Java is version 1.8.0_261, using 64-bit architecture.


Instance update failed because: Some artifacts marked as 'local' are missing their files:
D:/Applications/MultiMC/instances/Impact-4.9-1.15.2-OptiFine-HD_U_G1_pre26/libraries/OptiFine-1.15.2_HD_U_G1_pre26.jar

You need to either add the files, or removed the packages that require them.
You'll have to correct this problem manually.


Clipboard copy at: 15 Aug 2020 12:38:32 +0800
```

</details>

**System Info**
 - OS: Windows 10 Pro Insider (Update 2004, OS Build 19041.450)
 - Version: Installer 0.9.2 (downloaded from Releases page, EXE), Impact 4.9.1 with 1.15.2, OptiFine `1.15.2_HD_U_G1_pre26` (selected from drop-down menu, not custom path), latest MultiMC stable and dev version

**Additional context**
Installing with custom OptiFine installer path works, just the selection form the drop-down isn't working

**Comment by LeafHacker** [comment]
Thanks for the detailed bug report.

This is caused by [this line](https://github.com/ImpactDevelopment/Installer/blob/ce2e0c63c1c1cba57d53043e3ec52d1f9abc15f4/src/main/java/io/github/ImpactDevelopment/installer/optifine/OptiFineExisting.java#L44), which assumes the install mode is Vanilla and doesn't bother copying/installing optifine if it is already installed for the vanilla launcher.
