### ISSUE TITLE
How to use custom baritone jar file?

### ISSUE THREAD

**Issue by ralphchristianeclipse** [ImpactDevelopment/Installer#112]
Any ideas how to change the baritone version?

I've built a custom one from the source code but wanted to know how to use the built jar file.

**Comment by LeafHacker** [comment]
There's currently no "designed" way to do this with the installer. Would be a good feature though.

It is still possible if you know what your doing with the `.minecraft` directory, in particular installing artifacts into the `.minecraft/libraries` maven repo and messing about with Impact's version JSON that our installer puts in `.minecraft/versions`.

There is probably some documentation over on the baritone repo or wiki.

**Comment by ralphchristianeclipse** [comment]
@LeafHacker thanks already got this done by pointing directly on the libraries folder and putting my custom one :)
