### ISSUE TITLE
Optifine wont download for 1.16.5

### ISSUE THREAD

**Issue by Csquaredaap** [ImpactDevelopment/Installer#122]
I have the 1.16.5 nightly version and when i click include optifine it says null and I cant get optifine with the impact client

**Comment by notahumanthatisimportant** [comment]
You have to download it from optifine and in the installer specify the file path to optifine

**Comment by Dysproh** [comment]
The path can't be manually specified on 1.16.5.

**Comment by LeafHacker** [comment]
Duplicate of #126
