### ISSUE TITLE
Move install stuff to a Mojang/vanilla launcher class

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/Installer#14]
Installer.install() and Installer.isMinecraftLauncherOpen() are specific to the vanilla/mojang launcher and shouldn't be part of the _main_ class

_Maybe_ a wrapper method could exist somewhere generic like Installer that calls the relevant specific method for whatever launcher is configured in settings?

**Comment by leijurv** [comment]
On the one hand, isMinecraftLauncherOpen should be moved to inside the Vanilla specific installer (e.g. it doesnt make any sense for Forge mode), but on the other hand I like how 100% of the gui stuff is in the gui package =/

**Comment by LeafHacker** [comment]
But `isMinecraftLauncherOpen` isn't GUI stuff. The GUI simply _checks_ it if it is installing to a target where it matters.
