### ISSUE TITLE
If there is no OptiFine installed, link to the optifine download page

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/Installer#31]
maybe some text saying that theres no installed optifine for 1.13.2 or whatever, that it needs to be separately installed first, and a link to https://optifine.net/downloads

**Comment by LeafHacker** [comment]
TBH we should still have some text saying "newer versions _may_ be available from" or "No version found for 1.13.3, versions may be available at" depending on whether we found a compatible version installed or not
