### ISSUE TITLE
An error that comes up when I double click the installer 

### ISSUE THREAD

**Issue by CreepypastaFan** [ImpactDevelopment/Installer#34]
When I double click the file this error shows up
![20190524_014650](https://user-images.githubusercontent.com/51000253/58349624-c8ddff00-7e31-11e9-8917-89933bfa0425.jpg)

**To Reproduce**
1. I go to my files 
2. Double click the file 
3. I am asked what do I want to open the file with so I choose java
4. And the screenshot is what I get 

After all that I get the error that pops up (in the photo) I've tried to close out other browsers (including Minecraft) and this makes no difference 
![20190524_014650](https://user-images.githubusercontent.com/51000253/58349726-178b9900-7e32-11e9-864f-7bcfae7489b2.jpg)

 

**Desktop (please complete the following information):**
 - OS: windows 7
 - Browser Google chrome
 - Version (have no clue) 

It also comes up as a virus but I can choose to keep it, which it is impact, and I choose keep it.

**Comment by LeafHacker** [comment]
You are trying to open Impact Installer _with_ the Java installer.

The Java installer thinks "C:\Users\Owner-1\Downloads\installer-0.1.1-all.jar" has been passed to it as a CLI argument/flag/switch and is complaining that it doesn't have a flag/switch named that.

You need to instead do the following

1. Ensure Java is installed
2. Open Impact Installer with the version you installed (not its installer)

**Comment by leijurv** [comment]
ur literally rarted
