### ISSUE TITLE
Save As button for Forge installs

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/Installer#37]
**Is your feature request related to a problem? Please describe.**
Currently the forge target installs into the chosen minecraft directory `/mods/1.12.2/`. This is fine for 99% of the time, however there may be times when they just want to build an impact forge mod or save the mod in some arbitrary location or they might be using run directories in their forge profile(s).

**Describe the solution you'd like**
A "Save As" button (in addition to the main "Install" button) which allows the user full control over where the jar ends up.

**Describe alternatives you've considered**
Better handling of profile run directories being different to minecraft/launcher directories.

**Comment by leijurv** [comment]
im flattered that you think so highly of me that i would make it go into `mods/1.12.2/` but actually it just goes into `mods/` atm

**Comment by LeafHacker** [comment]
This was fixed by #98
