### ISSUE TITLE
Forge mode overwrites META-INF/MANIFEST.MF

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/Installer#43]
It shadows together many jars, and instead of dealing with merging all of their manifests it just has a hardcoded one that works. This is sort of necessary since changes to both lines of the manifest need to be made, so it wouldn't make sense as a replacement or anything. However, it's kinda yikes with the thought of removing client.json and putting that information in the MANIFEST, since the installer would discard it in forge mode.

**Comment by LeafHacker** [comment]
Fixed in f6f6f344f8cd9284e5440af6968a6cd0a21c90bd
