### ISSUE TITLE
Special error when Mc dir is /versions

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/Installer#55]
Have seen a couple times people instinctively picking minecraft/versions as the folder since that's where they're used to installing to, should detect this and change the standard "no vanilla detected" error to "plz select minecraft not version"

**Comment by 0-x-2-2** [comment]
what about the people who select the mods folder..........

**Comment by leijurv** [comment]
very good point

hell, lets just check both the selected directory and its parent directory, and have a special error if the parent directory is valid but the selected one isn't
