### ISSUE TITLE
Differentiate Optifine Versions

### ISSUE THREAD

**Issue by Cerbiac** [ImpactDevelopment/Installer#56]
**Is your feature request related to a problem? Please describe.**
When creating a version with and without OptiFine to make it easier to test the versions, they'll overwrite each other b/c they use the same folder name i.e. `1.12.2-Impact_4.6`.

**Describe the solution you'd like**
A additional "suffix" on the end that shows the version e.g. `-OptiFine_HD_U_E3` i.e. `1.12.2-Impact_4.6-OptiFine_HD_U_E3`.

**Describe alternatives you've considered**
The suffixes would be in the opposite order i.e. `1.12.2-OptiFine_HD_U_E3-Impact_4.6`.

**Additional context**
How I have it set up right now: 
![picture of my list of Minecraft installations.](https://imgur.com/P8Qi6ug.png)

**Comment by leijurv** [comment]
lol cerbiac made the exact same issue twice...? #53

**Comment by Cerbiac** [comment]
I looked to see if I made one, apparently I did, but still didn't see it at the time.
