### ISSUE TITLE
Configure launch4j bundled jre path to use Minecraft's JRE

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/Installer#59]
Like, literally use `%APPDATA%/.minecraft/runtime/jre-x64/jre.bundle/Contents/Home/bin/java` to run the installer, instead of requiring them to have java installed. launch4j can do this we just need to specify the path (I think).

**Comment by LeafHacker** [comment]
Should be simple assuming env vars work. [This stackoverflow question](https://stackoverflow.com/questions/7071133/how-to-bundle-a-jre-with-launch4j) shows that the normal launch4j XML config would have `<jre><path/></jre>` so the gradle pluggin probably mapps this to something like `jrePath`

**Comment by leijurv** [comment]
Turns out I was dead wrong on this, and that minecraft's bundled JRE is only placed in the minecraft directory on mac osx, on linux there isn't one and on windows it's bundled with the installer not the client smh

**Comment by leijurv** [comment]
(according to bwady)

**Comment by LeafHacker** [comment]
It's always bundled "with" the launcher, on windows it is _located_ with the launcher binaries while on osx it is located with the launcher config/resources. I have a working implementation for 64bit in the referenced PR.

**Comment by leijurv** [comment]
😻
