### ISSUE TITLE
travis is fucked

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/Installer#66]

**Comment by LastedGuide** [comment]
wth why did this happen, i cant make pull requests

**Comment by LeafHacker** [comment]
the optimize task is throwing NPEs for me locally, I assume travis is having the same problem

**Comment by LeafHacker** [comment]
Duplicate of #68

**Comment by 0-x-2-2** [comment]
crying and shaking the other pr is the duplicate this one was first.

**Comment by LeafHacker** [comment]
the other issue is more specific to the root cause.
