### ISSUE TITLE
Add a contributor copyright agreement to GitHub

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/Installer#72]
**Is your feature request related to a problem? Please describe.**
The installer is licensed GPL, which means it cannot be included in propietary works such as impact without a separate license from the copyright owner (or both works being by the same entity).

This isn't a problem since we own both impact and the Installer, however if we accept third party contributions then we are no longer the sole copyright holder and would need to seek permission to use the installer in impact from all installer contributers.

**Describe the solution you'd like**
A Canonical-style copyright waiver that ensures ImpactDevelopment or Brady remains the sole copyright holder. A GitHub bot would enforce signing the waiver on any pr from a new contributer.

**Describe alternatives you've considered**
Alternatively, as the copyright holder we could change the license to LGPL, before allowing others to contribute and hold copyright over their changes.

**Additional context**

**Comment by leijurv** [comment]
I'd rather make it lgpl but if a contributor license agreement works and you're sure, feel free

**Comment by LeafHacker** [comment]
let's go LGPL
