### ISSUE TITLE
Release proguard mappings

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/Installer#76]
**Is your feature request related to a problem? Please describe.**
Our proguard optimisations aren't too intrusive at the moment, but I guess including the mappings in the release could come in handy.

**Describe the solution you'd like**
Include proguard mappings in future releases

**Comment by 0-x-2-2** [comment]
Afaik the same jar is generated every time you obfuscate so you could just build locally 🤔

**Comment by leijurv** [comment]
we `-keep` everything but our libraries lol
everything in this actual installer package is kept xd
