### ISSUE TITLE
Change license to LGPLv3

### ISSUE THREAD

**Issue by S-B99** [ImpactDevelopment/Installer#87]
There doesn't seem to be a valid reason it's using specifically LGPLv2.1 currently.

Feel free to discuss this and give constructive criticism. This also prevents me from making a universal client installer that includes impact as LGPLv2.1 is not compatible with LGPLv3.

**Comment by 0-x-2-2** [comment]
> This also prevents me from making a universal client installer that includes impact as LGPLv2.1 is not compatible with LGPLv3.

It sounds like a valid reason to me. The Installer is only licensed at all under LGPL so people can contribute if they want. 

If someone wants to download Impact they should be downloading it from the official source, not some random sketchy discord server.

**Comment by S-B99** [comment]
My original plan was to include the installer itself in it, or download it on demand. I put together a half working on earlier on my discord, which at the moment can run the installer just like that.

Though I would prefer a better solution, such as instead having it build the jar as I assume the installer does, on demand.

**Comment by 0-x-2-2** [comment]
> My original plan was to include the installer itself in it, or download it on demand. I put together a half working on earlier on my discord, which at the moment can run the installer just like that.
> 
> Though I would prefer a better solution, such as instead having it build the jar as I assume the installer does, on demand.

What?

**Comment by S-B99** [comment]
Oh I completely misread your thing. Whatever yea.
