### ISSUE TITLE
Integration of older versions (1.9-1.11)

### ISSUE THREAD

**Issue by Sigha0160** [ImpactDevelopment/Installer#93]
**Is your feature request related to a problem? Please describe.**
I'm finding it difficult to source an older version of Impact for 1.10.2

**Describe the solution you'd like**
Ability to download or install the forge or vanilla(with optifine) installation of these legacy versions.

**Describe alternatives you've considered**
I've checked this GitHub for older versions as well as the old website.

**Additional context**
If you have older versions please send me a link to where I can find them! 

Thank you :)

**Comment by LeafHacker** [comment]
Versions of Impact prior to 4.0 are not available because they contain Minecraft and OptiFine. You are not allowed to distribute other people's stuff without permission, so distributing Impact pre-4.0 violates both Mojang's and OptiFine's copyright.
