### ISSUE TITLE
The Installer fetches releases.json over HTTP instead of HTTPS, allowing a stale caching server response (Or arbitrary changes to the manifest)

### ISSUE THREAD

**Issue by ipaqmaster** [ImpactDevelopment/Installer#99]
**Describe the bug**
On line 44 of `Installer/src/main/java/io/github/ImpactDevelopment/installer/github/Github.java` HTTP is used before HTTPS in regards to fetching https://impactclient.net/releases.json.

This allows caching servers to return stale results from previous downloads of the manifest and worse it allows someone to modify the manifest before it gets to you allowing arbitrary URLs to be specified during the Install process which can be dangerous.

I recommend this be changed to HTTPS by default. Use http as the fallback if you must, but don't make it the first option.

**To Reproduce**
1. Have previously used the Impact Installer through a http proxy (Either a set proxy or transparently)
2. Launch the Installer again a month later
3. Witness stale or modified version listings

**Expected behavior**
One would expect the latest 5 nightly builds to show up, but they didn't as a transparent caching server held onto the manifest from a month ago. This would not have happened over HTTPS.

**Screenshots?**
Imagine the nightly build list.. but showing nightly builds from a month ago and thinking it's correct.

**Desktop (please complete the following information):**
 - OS: Archlinux - Kernel 5.6.7
 - Installer Version: Installer 0.8.6 (Current)

**Additional context**

1. To summarize, a caching server was allowed to intercept the releases.json fetch and returned stale entries from April 2020 which was confusing. This was caused by the Installer fetching over HTTP first instead of HTTPS as it's first connection attempt.

2. See my original github Issue [HERE](https://github.com/ImpactDevelopment/ImpactIssues/issues/2260) where I found this out.

**Comment by leijurv** [comment]
The security issue is actually a nonissue (see https://github.com/ImpactDevelopment/Installer/blob/master/src/main/resources/keys.asc and https://github.com/ImpactDevelopment/Installer/blob/master/src/main/java/io/github/ImpactDevelopment/installer/utils/GPG.java).

Can you say more about this cache? Is this an additional HTTP cache beyond our CDN (cloudflare)?

I'm actually more inclined to fix this by changing the Cache-Control header server-side to 1 day, or something like that

**Comment by ipaqmaster** [comment]
I think changing the Cache-Control header to match at most how many days back the nightly builds go (5 days) could be a good idea however I don't have information on where where this caching server was in my encounter so for all I know it may not even  honoring the Cache-Control header in the first place. Given the dates I was seeing (In my previous Issue) were from April.

curl -I shows it's currently set to `cache-control: public, max-age=86400` which I'm pretty sure is 1 day. So we're already looking at a scenario where the control header were ignored.

**Comment by leijurv** [comment]
right, that commit there ^ https://github.com/ImpactDevelopment/ImpactServer/commit/26ddf9aca6c7c8bccd332d8e1fb7027389547f8b was where I changed it to one day. it was previously 1 year lol

**Comment by leijurv** [comment]
this is because we automatically purge (using cloudflare's api) whenever something changes. this is because we're cheap and just have one free-tier heroku instance, it can't take the load of all the requests lol

**Comment by ipaqmaster** [comment]
Ah I missed it lol. Ok, hopefully that did the trick.

**Comment by ipaqmaster** [comment]
Fetching again today shows me last weeks nightly snapshots. I see cache-control is still set to a day showing that whatevers between me and your CDN isn't honoring that header.

You've mentioned your visitor load leaves good reason to promote caching of the webserver but is there any hope for something like an optional "force https" checkbox as a workaround for connections forced to go through a transparent proxy? Even a check on whether the returned json is stale and a retry over https would solve this situation.

**Comment by leijurv** [comment]
i mean, like, turn on a vpn or something lol

or clone this repo, add the `s`, and ./gradlew build

lowkey........ "there's something between me and your site that is MITMing http" is a user error, not an issue on my end

**Comment by ipaqmaster** [comment]
A VPN has been the current workaround for me as I don't have any other connections outside my ISP. I understand this situation isn't a fault of your Installer but a detection could be implemented without extra effort from users.

As for building it myself I succeeded in building it with Gradle last week; however it didn't show the nightly builds, is there something I need to set for them to show by default?
